spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hearmeout
    username: root
    password: mysecretpassword

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"