server:
  port: ${PORT}
  servlet:
    context-path: /api/v2

spring:
  application:
    name: HearMeOut_Backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:

    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual

jwt:
  secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%X{requestMethod} %X{requestURI}] %-5level %logger - %msg%n"

admin:
  mail: ${ADMIN_MAIL}

cookie:
  creation:
    secure: ${COOKIE_SECURE}
    same-site: ${COOKIE_SAMESITE}