server:
  port: ${PORT}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: HearMeOut_Backend
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "userRegistered:com.project.hearmeout_backend.common_lib.event_dto.UserRegisteredEvent,passwordResetOtp:com.project.hearmeout_backend.common_lib.event_dto.PasswordResetOtpEvent,verificationOtp:com.project.hearmeout_backend.common_lib.event_dto.VerificationOtpEvent"
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: latest
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.project.hearmeout_backend.common_lib.event_dto"
        spring.json.type.mapping: "userRegistered:com.project.hearmeout_backend.common_lib.event_dto.UserRegisteredEvent,passwordResetOtp:com.project.hearmeout_backend.common_lib.event_dto.PasswordResetOtpEvent,verificationOtp:com.project.hearmeout_backend.common_lib.event_dto.VerificationOtpEvent"

jwt:
  secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%X{requestMethod} %X{requestURI}] %-5level %logger - %msg%n"
